config/routes.rb
Todo::Application.routes.draw do

  root to: 'pages#home'

  resources :tasks, except: [:index]
end
  

app/models/task.rb
class Task < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@tasks = Task.all
 end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def new
		@task = Task.new
 end

def create 
	@task = Task.create(task_params)
	redirect_to root_path
end
private
def task_params
	params.require(:task).permit(:title, :note, :completed)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Todo
    = stylesheet_link_tag   "application", media: "all"
    = javascript_include_tag    "application"
    = csrf_meta_tags
  %body
    .row-fluid
      .span10.offset1
        .hero-unit.text-center
          %h1
            ToDo
          %p
            Welcome to the tutorial's ToDo application
        = link_to 'New Task', new_task_path, class: 'btn btn-primary', remote: true
    = yield

app/views/pages/home.html.haml
.container
  - if @tasks.empty?
    %span.text-warning There are no tasks!
  - else
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th Title
          %th Created at
          %th Completed
      %tbody
        - @tasks.each do |task|
          %tr
            %td
              %strong= task.title
            %td.text-info= task.created_at
            %td.text-success= task.completed

app/views/tasks/_task_form.html.haml
.modal-header
   %h1 New Task
 = simple_form_for task, class: 'clearfix' do |f|
   .modal-body
     = f.input :title
     = f.input :note
     = f.input :completed, as: :string, input_html: {class: 'datepicker'}
   .modal-footer
     = f.submit 'Save', class: 'btn btn-primary'

app/views/tasks/new.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task}) %>'); 
m.modal('show');
$('#modal').integrateDatepicker();